//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3dCartImportConsole.CKOrderStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://coverkingprod.cloudapp.net/", ConfigurationName="CKOrderStatus.Order_StatusSoap")]
    public interface Order_StatusSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_Orders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _3dCartImportConsole.CKOrderStatus.Orders_response Get_Orders(string Lastname, string Zip, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_Orders", ReplyAction="*")]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_OrdersAsync(string Lastname, string Zip, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_Orders_by_OrderNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _3dCartImportConsole.CKOrderStatus.Orders_response Get_Orders_by_OrderNo(string OrdersNo, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_Orders_by_OrderNo", ReplyAction="*")]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_Orders_by_OrderNoAsync(string OrdersNo, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_Orders_by_PO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _3dCartImportConsole.CKOrderStatus.Orders_response Get_Orders_by_PO(string POs, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_Orders_by_PO", ReplyAction="*")]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_Orders_by_POAsync(string POs, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_OrderStatus_by_PO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _3dCartImportConsole.CKOrderStatus.Orders_response Get_OrderStatus_by_PO(string APIKEY, string POs, string DealerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Get_OrderStatus_by_PO", ReplyAction="*")]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_OrderStatus_by_POAsync(string APIKEY, string POs, string DealerID);
        
        // CODEGEN: Generating message contract since message part namespace (usaparts) does not match the default value (http://coverkingprod.cloudapp.net/)
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/CustomSet1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SomeClass")]
        _3dCartImportConsole.CKOrderStatus.CustomSet1Response CustomSet1(_3dCartImportConsole.CKOrderStatus.CustomSet1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/CustomSet1", ReplyAction="*")]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.CustomSet1Response> CustomSet1Async(_3dCartImportConsole.CKOrderStatus.CustomSet1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Save_for_notifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _3dCartImportConsole.CKOrderStatus.Orders_response Save_for_notifications(string OrderNo, string Email, string Phone, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Save_for_notifications", ReplyAction="*")]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Save_for_notificationsAsync(string OrderNo, string Email, string Phone, string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Notification_Status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Notification_Status(string MessageStatus, string ApiVersion, string SmsSid, string SmsStatus, string To, string From, string MessageSid, string AccountSid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://coverkingprod.cloudapp.net/Notification_Status", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Notification_StatusAsync(string MessageStatus, string ApiVersion, string SmsSid, string SmsStatus, string To, string From, string MessageSid, string AccountSid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coverkingprod.cloudapp.net/")]
    public partial class Orders_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Orders[] orders_listField;
        
        private string error_MessageField;
        
        private string error_CodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Orders[] Orders_list {
            get {
                return this.orders_listField;
            }
            set {
                this.orders_listField = value;
                this.RaisePropertyChanged("Orders_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_Message {
            get {
                return this.error_MessageField;
            }
            set {
                this.error_MessageField = value;
                this.RaisePropertyChanged("Error_Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error_Code {
            get {
                return this.error_CodeField;
            }
            set {
                this.error_CodeField = value;
                this.RaisePropertyChanged("Error_Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coverkingprod.cloudapp.net/")]
    public partial class Orders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Parts[] parts_listField;
        
        private string order_noField;
        
        private string zipField;
        
        private System.DateTime order_dateField;
        
        private string cityField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Parts[] Parts_list {
            get {
                return this.parts_listField;
            }
            set {
                this.parts_listField = value;
                this.RaisePropertyChanged("Parts_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Order_no {
            get {
                return this.order_noField;
            }
            set {
                this.order_noField = value;
                this.RaisePropertyChanged("Order_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Order_date {
            get {
                return this.order_dateField;
            }
            set {
                this.order_dateField = value;
                this.RaisePropertyChanged("Order_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://coverkingprod.cloudapp.net/")]
    public partial class Parts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customer_POField;
        
        private System.DateTime order_dateField;
        
        private string order_NoField;
        
        private string serial_NoField;
        
        private string descriptionField;
        
        private string yearField;
        
        private string makeField;
        
        private string modelField;
        
        private string optionField;
        
        private string material_DescriptionField;
        
        private string shipping_agent_usedField;
        
        private string shipping_agent_service_usedField;
        
        private string years_fromField;
        
        private string years_toField;
        
        private string package_linkField;
        
        private string package_NoField;
        
        private string statusField;
        
        private System.Nullable<byte> cancelledField;
        
        private string itemNoField;
        
        private string variantIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Customer_PO {
            get {
                return this.customer_POField;
            }
            set {
                this.customer_POField = value;
                this.RaisePropertyChanged("Customer_PO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Order_date {
            get {
                return this.order_dateField;
            }
            set {
                this.order_dateField = value;
                this.RaisePropertyChanged("Order_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Order_No {
            get {
                return this.order_NoField;
            }
            set {
                this.order_NoField = value;
                this.RaisePropertyChanged("Order_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Serial_No {
            get {
                return this.serial_NoField;
            }
            set {
                this.serial_NoField = value;
                this.RaisePropertyChanged("Serial_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
                this.RaisePropertyChanged("Make");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("Model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
                this.RaisePropertyChanged("Option");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Material_Description {
            get {
                return this.material_DescriptionField;
            }
            set {
                this.material_DescriptionField = value;
                this.RaisePropertyChanged("Material_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Shipping_agent_used {
            get {
                return this.shipping_agent_usedField;
            }
            set {
                this.shipping_agent_usedField = value;
                this.RaisePropertyChanged("Shipping_agent_used");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Shipping_agent_service_used {
            get {
                return this.shipping_agent_service_usedField;
            }
            set {
                this.shipping_agent_service_usedField = value;
                this.RaisePropertyChanged("Shipping_agent_service_used");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Years_from {
            get {
                return this.years_fromField;
            }
            set {
                this.years_fromField = value;
                this.RaisePropertyChanged("Years_from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Years_to {
            get {
                return this.years_toField;
            }
            set {
                this.years_toField = value;
                this.RaisePropertyChanged("Years_to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Package_link {
            get {
                return this.package_linkField;
            }
            set {
                this.package_linkField = value;
                this.RaisePropertyChanged("Package_link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Package_No {
            get {
                return this.package_NoField;
            }
            set {
                this.package_NoField = value;
                this.RaisePropertyChanged("Package_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<byte> Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
                this.RaisePropertyChanged("Cancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
                this.RaisePropertyChanged("ItemNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string VariantID {
            get {
                return this.variantIDField;
            }
            set {
                this.variantIDField = value;
                this.RaisePropertyChanged("VariantID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="usaparts")]
    public partial class CustomSet1_parts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trackingNumberField;
        
        private string sKUField;
        
        private string mFGPartField;
        
        private string supersededSkuField;
        
        private string brandField;
        
        private string orderedQtylField;
        
        private string itemQtyField;
        
        private string backOrderedQuantityField;
        
        private string itemAmountField;
        
        private string extendedPriceField;
        
        private string handlingChargesField;
        
        private string otherChargesField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MFGPart {
            get {
                return this.mFGPartField;
            }
            set {
                this.mFGPartField = value;
                this.RaisePropertyChanged("MFGPart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SupersededSku {
            get {
                return this.supersededSkuField;
            }
            set {
                this.supersededSkuField = value;
                this.RaisePropertyChanged("SupersededSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("Brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OrderedQtyl {
            get {
                return this.orderedQtylField;
            }
            set {
                this.orderedQtylField = value;
                this.RaisePropertyChanged("OrderedQtyl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ItemQty {
            get {
                return this.itemQtyField;
            }
            set {
                this.itemQtyField = value;
                this.RaisePropertyChanged("ItemQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BackOrderedQuantity {
            get {
                return this.backOrderedQuantityField;
            }
            set {
                this.backOrderedQuantityField = value;
                this.RaisePropertyChanged("BackOrderedQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ItemAmount {
            get {
                return this.itemAmountField;
            }
            set {
                this.itemAmountField = value;
                this.RaisePropertyChanged("ItemAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ExtendedPrice {
            get {
                return this.extendedPriceField;
            }
            set {
                this.extendedPriceField = value;
                this.RaisePropertyChanged("ExtendedPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string HandlingCharges {
            get {
                return this.handlingChargesField;
            }
            set {
                this.handlingChargesField = value;
                this.RaisePropertyChanged("HandlingCharges");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OtherCharges {
            get {
                return this.otherChargesField;
            }
            set {
                this.otherChargesField = value;
                this.RaisePropertyChanged("OtherCharges");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="usaparts")]
    public partial class ShipUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pONumberField;
        
        private string shipUniteSequenceField;
        
        private string shipUnitTotalIdField;
        
        private string supplierInvoiceNumberField;
        
        private string shippingCompanyField;
        
        private string trackingNumberField;
        
        private string estimatedShipDateField;
        
        private string shipDateField;
        
        private string freightField;
        
        private string whsidField;
        
        private CustomSet1_parts[] partsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PONumber {
            get {
                return this.pONumberField;
            }
            set {
                this.pONumberField = value;
                this.RaisePropertyChanged("PONumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ShipUniteSequence {
            get {
                return this.shipUniteSequenceField;
            }
            set {
                this.shipUniteSequenceField = value;
                this.RaisePropertyChanged("ShipUniteSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShipUnitTotalId {
            get {
                return this.shipUnitTotalIdField;
            }
            set {
                this.shipUnitTotalIdField = value;
                this.RaisePropertyChanged("ShipUnitTotalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SupplierInvoiceNumber {
            get {
                return this.supplierInvoiceNumberField;
            }
            set {
                this.supplierInvoiceNumberField = value;
                this.RaisePropertyChanged("SupplierInvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ShippingCompany {
            get {
                return this.shippingCompanyField;
            }
            set {
                this.shippingCompanyField = value;
                this.RaisePropertyChanged("ShippingCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EstimatedShipDate {
            get {
                return this.estimatedShipDateField;
            }
            set {
                this.estimatedShipDateField = value;
                this.RaisePropertyChanged("EstimatedShipDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
                this.RaisePropertyChanged("ShipDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Freight {
            get {
                return this.freightField;
            }
            set {
                this.freightField = value;
                this.RaisePropertyChanged("Freight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Whsid {
            get {
                return this.whsidField;
            }
            set {
                this.whsidField = value;
                this.RaisePropertyChanged("Whsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public CustomSet1_parts[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="usaparts")]
    public partial class Order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pONumberField;
        
        private string pODateField;
        
        private string statusField;
        
        private ShipUnit[] shipUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PONumber {
            get {
                return this.pONumberField;
            }
            set {
                this.pONumberField = value;
                this.RaisePropertyChanged("PONumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PODate {
            get {
                return this.pODateField;
            }
            set {
                this.pODateField = value;
                this.RaisePropertyChanged("PODate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ShipUnit[] ShipUnit {
            get {
                return this.shipUnitField;
            }
            set {
                this.shipUnitField = value;
                this.RaisePropertyChanged("ShipUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="usaparts")]
    public partial class OrderStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_codeField;
        
        private string error_messageField;
        
        private Order[] orderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
                this.RaisePropertyChanged("Error_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_message {
            get {
                return this.error_messageField;
            }
            set {
                this.error_messageField = value;
                this.RaisePropertyChanged("Error_message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Order[] Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomSet1", WrapperNamespace="http://coverkingprod.cloudapp.net/", IsWrapped=true)]
    public partial class CustomSet1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coverkingprod.cloudapp.net/", Order=0)]
        public string PO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://coverkingprod.cloudapp.net/", Order=1)]
        public string Key;
        
        public CustomSet1Request() {
        }
        
        public CustomSet1Request(string PO, string Key) {
            this.PO = PO;
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomSet1Response", WrapperNamespace="http://coverkingprod.cloudapp.net/", IsWrapped=true)]
    public partial class CustomSet1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="usaparts", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="usaparts")]
        public _3dCartImportConsole.CKOrderStatus.OrderStatusResponse SomeClass;
        
        public CustomSet1Response() {
        }
        
        public CustomSet1Response(_3dCartImportConsole.CKOrderStatus.OrderStatusResponse SomeClass) {
            this.SomeClass = SomeClass;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Order_StatusSoapChannel : _3dCartImportConsole.CKOrderStatus.Order_StatusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Order_StatusSoapClient : System.ServiceModel.ClientBase<_3dCartImportConsole.CKOrderStatus.Order_StatusSoap>, _3dCartImportConsole.CKOrderStatus.Order_StatusSoap {
        
        public Order_StatusSoapClient() {
        }
        
        public Order_StatusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Order_StatusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Order_StatusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Order_StatusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _3dCartImportConsole.CKOrderStatus.Orders_response Get_Orders(string Lastname, string Zip, string Key) {
            return base.Channel.Get_Orders(Lastname, Zip, Key);
        }
        
        public System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_OrdersAsync(string Lastname, string Zip, string Key) {
            return base.Channel.Get_OrdersAsync(Lastname, Zip, Key);
        }
        
        public _3dCartImportConsole.CKOrderStatus.Orders_response Get_Orders_by_OrderNo(string OrdersNo, string Key) {
            return base.Channel.Get_Orders_by_OrderNo(OrdersNo, Key);
        }
        
        public System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_Orders_by_OrderNoAsync(string OrdersNo, string Key) {
            return base.Channel.Get_Orders_by_OrderNoAsync(OrdersNo, Key);
        }
        
        public _3dCartImportConsole.CKOrderStatus.Orders_response Get_Orders_by_PO(string POs, string Key) {
            return base.Channel.Get_Orders_by_PO(POs, Key);
        }
        
        public System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_Orders_by_POAsync(string POs, string Key) {
            return base.Channel.Get_Orders_by_POAsync(POs, Key);
        }
        
        public _3dCartImportConsole.CKOrderStatus.Orders_response Get_OrderStatus_by_PO(string APIKEY, string POs, string DealerID) {
            return base.Channel.Get_OrderStatus_by_PO(APIKEY, POs, DealerID);
        }
        
        public System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Get_OrderStatus_by_POAsync(string APIKEY, string POs, string DealerID) {
            return base.Channel.Get_OrderStatus_by_POAsync(APIKEY, POs, DealerID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _3dCartImportConsole.CKOrderStatus.CustomSet1Response _3dCartImportConsole.CKOrderStatus.Order_StatusSoap.CustomSet1(_3dCartImportConsole.CKOrderStatus.CustomSet1Request request) {
            return base.Channel.CustomSet1(request);
        }
        
        public _3dCartImportConsole.CKOrderStatus.OrderStatusResponse CustomSet1(string PO, string Key) {
            _3dCartImportConsole.CKOrderStatus.CustomSet1Request inValue = new _3dCartImportConsole.CKOrderStatus.CustomSet1Request();
            inValue.PO = PO;
            inValue.Key = Key;
            _3dCartImportConsole.CKOrderStatus.CustomSet1Response retVal = ((_3dCartImportConsole.CKOrderStatus.Order_StatusSoap)(this)).CustomSet1(inValue);
            return retVal.SomeClass;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.CustomSet1Response> _3dCartImportConsole.CKOrderStatus.Order_StatusSoap.CustomSet1Async(_3dCartImportConsole.CKOrderStatus.CustomSet1Request request) {
            return base.Channel.CustomSet1Async(request);
        }
        
        public System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.CustomSet1Response> CustomSet1Async(string PO, string Key) {
            _3dCartImportConsole.CKOrderStatus.CustomSet1Request inValue = new _3dCartImportConsole.CKOrderStatus.CustomSet1Request();
            inValue.PO = PO;
            inValue.Key = Key;
            return ((_3dCartImportConsole.CKOrderStatus.Order_StatusSoap)(this)).CustomSet1Async(inValue);
        }
        
        public _3dCartImportConsole.CKOrderStatus.Orders_response Save_for_notifications(string OrderNo, string Email, string Phone, string Key) {
            return base.Channel.Save_for_notifications(OrderNo, Email, Phone, Key);
        }
        
        public System.Threading.Tasks.Task<_3dCartImportConsole.CKOrderStatus.Orders_response> Save_for_notificationsAsync(string OrderNo, string Email, string Phone, string Key) {
            return base.Channel.Save_for_notificationsAsync(OrderNo, Email, Phone, Key);
        }
        
        public string Notification_Status(string MessageStatus, string ApiVersion, string SmsSid, string SmsStatus, string To, string From, string MessageSid, string AccountSid) {
            return base.Channel.Notification_Status(MessageStatus, ApiVersion, SmsSid, SmsStatus, To, From, MessageSid, AccountSid);
        }
        
        public System.Threading.Tasks.Task<string> Notification_StatusAsync(string MessageStatus, string ApiVersion, string SmsSid, string SmsStatus, string To, string From, string MessageSid, string AccountSid) {
            return base.Channel.Notification_StatusAsync(MessageStatus, ApiVersion, SmsSid, SmsStatus, To, From, MessageSid, AccountSid);
        }
    }
}
